networks:
  pg-network:

services:
  pgdatabase:
    image: postgres:13
    container_name: pg-database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/workspaces/Zoomcamp2025/week_1_setup/2_docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-network

  pgcli:
    build:
      context: .
      dockerfile: Dockerfile.pgcli
    depends_on:
      - pgdatabase
    environment:
      - PGPASSWORD=root
    command: tail -f /dev/null
    networks:
      - pg-network